
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import  "../../../app/globals.css"

import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import SideBar from "@/components/SideBar";
import BankProvider from "@/context/BankProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-background' , inter.className)}>
        <BankProvider>
             
        <div className="w-full h-screen max-h-screen flex">
          <SideBar/>
        {children}
        </div>
        </BankProvider>
  
     
          
      
      
        
        
        </body>
    </html>
  );
}